[project]
name = "jupyter-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.4",
    "matplotlib>=3.10.3",
    "rioxarray>=0.19.0",
]
